language: c
compiler:
  - gcc
  - clang

before_script: ./autogen.sh

matrix:
  fast_finish: true
      env:
        - TEST = debug
        - TEST = singlethreaded 
        - TEST = dtls 
        - TEST = ipv6 
        - TEST = bump 
        - TEST = leanpsk
        - TEST = bigcache 
        - TEST = hugecache
        - TEST = smallcache 
        - TEST = savesession 
        - TEST = savecert 
        - TEST = atomicuser 
        - TEST = pkcallbacks 
        - TEST = sniffer 
        - TEST = aesgcm 
        - TEST = aesccm 
        - TEST = aesni 
        - TEST = camellia 
        - TEST = md2 
        - TEST = nullcipher 
        - TEST = ripemd 
        - TEST = blake2 
        - TEST = sha512
        - TEST = sessioncerts 
        - TEST = keygen 
        - TEST = certgen 
        - TEST = sep 
        - TEST = dsa 
        - TEST = ecc 
        - TEST = psk
        - TEST = stacksize 
        - TEST = md4 
        - TEST = pwdbased 
        - TEST = hc128 
        - TEST = rabbit 
        - TEST = webserver 
        - TEST = ocsp 
        - TEST = crl 
        - TEST = crl-monitor 
        - TEST = ntru 
        - TEST = sni 
        - TEST = maxfragment 
        - TEST = truncatedhmac 
        - TEST = testcert 
        - TEST = fastmath 
        - TEST = fasthugemath 
        - TEST = mcapi 
    
script: "./configure --enable-$TEST && make"
