language: c
compiler:
  - clang

before_script: ./autogen.sh

env:
- Option=""
- Option="--enable-debug"
- Option="--enable-singlethreaded"
- Option="--enable-dtls"
- Option="--enable-opensslextra"
- Option="--enable-ipv6"
- Option="--enable-bump"
- Option="--enable-bigcache"
- Option="--enable-hugecache"
- Option="--enable-smallcache"
- Option="--enable-savesession"
- Option="--enable-savecert"
- Option="--enable-atomicuser"
- Option="--enable-pkcallbacks"
- Option="--enable-sniffer"
- Option="--enable-aesgcm"
- Option="--enable-aesccm"
- Option="--enable-aesni"
- Option="--enable-camellia"
- Option="--enable-md2"
- Option="--enable-nullcipher"
- Option="--enable-ripemd"
- Option="--enable-blake2"
- Option="--enable-sha512"
- Option="--enable-sessioncerts"
- Option="--enable-keygen"
- Option="--enable-certgen"
- Option="--enable-sep"
- Option="--enable-dsa"
- Option="--enable-ecc"
- Option="--enable-psk"
- Option="--enable-stacksize"
- Option="--enable-md4"
- Option="--enable-pwdbased"
- Option="--enable-hc128"
- Option="--enable-rabbit"
- Option="--enable-webserver"
- Option="--enable-ocsp"
- Option="--enable-crl"
- Option="--enable-sni"
- Option="--enable-maxfragment"
- Option="--enable-truncatedhmac"
- Option="--enable-tlsx --enable-ecc"
- Option="--enable-fastmath"
- Option="--disable-fastmath"
- Option="--enable-fasthugemath"
- Option="--enable-mcapi --enable-sha512 --enable-ecc --with-libz"
- Option="--enable-opensslextra --enable-ecc --enable-dtls --enable-aesgcm --enable-aesccm --enable-hc128 --enable-sniffer --enable-psk --enable-rabbit --enable-camellia --enable-sha512 --enable-crl --enable-ocsp --enable-savesession --enable-savecert --enable-atomicuser --enable-pkcallbacks --enable-scep"

script: ./configure $Option && make && make test
