language: c
compiler:
  - gcc
  - clang

before_script: ./autogen.sh

script: ./configure --enable-debug && make

after_script: if[ after_success = 1]; then
              echo Debug Failed!!!
              else
              echo Debug Passed
              fi
