language: c
compiler:
  - gcc
  - clang

before_script: ./autogen.sh

matrix:
  fast_finish: true
  include: 
    - env:  TEST = debug
    - env:  TEST = singlethreaded 
    - env:  TEST = dtls 
    - env:  TEST = ipv6 
    - env:  TEST = bump 
    - env:  TEST = leanpsk
    - env:  TEST = bigcache 
    - env:  TEST = hugecache
    - env:  TEST = smallcache 
    - env:  TEST = savesession 
    - env:  TEST = savecert 
    - env: TEST = atomicuser 
    - env: TEST = pkcallbacks 
    - env: TEST = sniffer 
    - env: TEST = aesgcm 
    - env: TEST = aesccm 
    - env: TEST = aesni 
    - env: TEST = camellia 
    - env: TEST = md2 
    - env: TEST = nullcipher 
    - env: TEST = ripemd 
    - env: TEST = blake2 
    - env: TEST = sha512
    - env: TEST = sessioncerts 
    - env: TEST = keygen 
    - env: TEST = certgen 
    - env: TEST = sep 
    - env: TEST = dsa 
    - env: TEST = ecc 
    - env: TEST = psk
    - env: TEST = stacksize 
    - env: TEST = md4 
    - env: TEST = pwdbased 
    - env: TEST = hc128 
    - env: TEST = rabbit 
    - env: TEST = webserver 
    - env: TEST = ocsp 
    - env: TEST = crl 
    - env: TEST = crl-monitor 
    - env: TEST = ntru 
    - env: TEST = sni 
    - env: TEST = maxfragment 
    - env: TEST = truncatedhmac 
    - env: TEST = testcert 
    - env: TEST = fastmath 
    - env: TEST = fasthugemath 
    - env: TEST = mcapi 
    
script: "./configure --enable-$TEST && make"
