language: c
compiler:
  - gcc
  - clang

before_script: ./autogen.sh
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "d9Vcwaox80TgfeG3_tairQ"

addons:
  coverity_scan:
    project:
      name: "Nathanrauch/cyassl"
    notification_email: nathan@wolfssl.com
    build_command_prepend: "./configure"
    build_command: "make"
    branch_pattern: "coverity_scan"
script: make
