language: c
compiler:
  - gcc
  - clang
# Change this to your needs
script: 
  - ./autogen.sh && ./configure --disable-examples --enable-debug --enable-dtls --enable-ipv6 --enable-bump --enable-leanpsk --enable-bigcache --enable-savesession --enable-savecert --enable-aesgcm --enable-keygen --enable-certgen --enable-ocsp --enable-crl --enable-crl-monitor --enable-sni --enable-truncatedhmac --enable-testcert  && make
