language: c
compiler:
  - clang

before_script: ./autogen.sh

env:
- Option=debug
- Option=singlethreaded
- Option=dtls
- Option=opensslextra
- Option=ipv6
- Option=bump
- Option=bigcache
- Option=hugecache
- Option=smallcache
- Option=savesession
- Option=savecert
- Option=atomicuser
- Option=pkcallbacks
- Option=sniffer
- Option=aesgcm
- Option=aesccm
- Option=aesni
- Option=camellia
- Option=md2
- Option=nullcipher
- Option=ripemd
- Option=blake2
- Option=sha512
- Option=sessioncerts
- Option=keygen
- Option=certgen
- Option=sep
- Option=dsa
- Option=ecc
- Option=psk
- Option=stacksize
- Option=md4
- Option=pwdbased
- Option=hc128
- Option=rabbit
- Option=webserver
- Option=ocsp
- Option=crl
- Option=sni
- Option=maxfragment
- Option=truncatedhmac
- Option="tlsx --enable-ecc"
- Option=fasthmath
- Option=fasthugemath
- Option="mcapi --enable-sha512 --enable-ecc --with-libz"

script: ./configure --enable-$Option && make && make test
