language: c
compiler:
  - gcc
  - clang

before_script: ./autogen.sh
matrix:
  fast_finish: true
  include:
  - env: TEST_SUITE=debug
  - env: TEST_SUITE=singlethreaded
  - env: TEST_SUITE=dtls
  - env: TEST_SUITE=opensslextra
  - env: TEST_SUITE=ipv6
  - env: TEST_SUITE=bump
  - env: TEST_SUITE=leanpsk
  - env: TEST_SUITE=bigcache
  - env: TEST_SUITE=hugecache
  - env: TEST_SUITE=smallcache
  - env: TEST_SUITE=savesession
  - env: TEST_SUITE=savecert
  - env: TEST_SUITE=atomicuser
  - env: TEST_SUITE=pkcallbacks
  - env: TEST_SUITE=sniffer
  - env: TEST_SUITE=aesgcm
  - env: TEST_SUITE=aesccm
  - env: TEST_SUITE=aesni
  - env: TEST_SUITE=camellia
  - env: TEST_SUITE=md2
  - env: TEST_SUITE=nullcipher
  - env: TEST_SUITE=ripemd
  - env: TEST_SUITE=blake2
  - env: TEST_SUITE=sha512
  - env: TEST_SUITE=sessioncerts
  - env: TEST_SUITE=keygen
  - env: TEST_SUITE=certgen
  - env: TEST_SUITE=sep
  - env: TEST_SUITE=dsa
  - env: TEST_SUITE=ecc
  - env: TEST_SUITE=psk
  - env: TEST_SUITE=stacksize
  - env: TEST_SUITE=md4
  - env: TEST_SUITE=pwdbased
  - env: TEST_SUITE=hc128
  - env: TEST_SUITE=rabbit
  - env: TEST_SUITE=webserver
  - env: TEST_SUITE=ocsp
  - env: TEST_SUITE=crl
  - env: TEST_SUITE=crl-monitor
  - env: TEST_SUITE=ntru
  - env: TEST_SUITE=sni
  - env: TEST_SUITE=maxfragment
  - env: TEST_SUITE=truncatedhmac
  - env: TEST_SUITE=tlsx
  - env: TEST_SUITE=testcert
  - env: TEST_SUITE=fastmath
  - env: TEST_SUITE=fasthugemath
  - env: TEST_SUITE=mcapi
script: ./configure --enable-$TEST_SUITE && make
