language: c
compiler:
  - gcc
  - clang

before_script: ./autogen.sh

script:  ./configure --enable-debug && make
        - echo Debug Option
        ./configure --enable-singlethreaded && make
        - echo SingleThread Option
