language: c
compiler:
  - gcc
  - clang

before_script: ./autogen.sh

matrix:
  fast_finish: true
  include:
    - env: CONFIG = --enable-debug
    - env: CONFIG = --enable-singlethreaded
    - env: CONFIG = --enable-dtls
    - env: CONFIG = --enable-ipv6
    - env: CONFIG = --enable-bump
    - env: CONFIG = --enable-leanpsk
    - env: CONFIG = --enable-bigcache
    - env: CONFIG = --enable-hugecache
    - env: CONFIG = --enable-smallcache
    - env: CONFIG = --enable-savesession
    - env: CONFIG = --enable-savecert
    - env: CONFIG = --enable-atomicuser
    - env: CONFIG = --enable-pkcallbacks
    - env: CONFIG = --enable-sniffer
    - env: CONFIG = --enable-aesgcm
    - env: CONFIG = --enable-aesccm
    - env: CONFIG = --enable-aesni
    - env: CONFIG = --enable-camellia
    - env: CONFIG = --enable-md2
    - env: CONFIG = --enable-nullcipher
    - env: CONFIG = --enable-ripemd
    - env: CONFIG = --enable-blake2
    - env: CONFIG = --enable-sha512
    - env: CONFIG = --enable-sessioncerts
    - env: CONFIG = --enable-keygen
    - env: CONFIG = --enable-certgen
    - env: CONFIG = --enable-sep
    - env: CONFIG = --enable-dsa
    - env: CONFIG = --enable-ecc
    - env: CONFIG = --enable-psk
    - env: CONFIG = --enable-stacksize
    - env: CONFIG = --enable-md4
    - env: CONFIG = --enable-pwdbased
    - env: CONFIG = --enable-hc128
    - env: CONFIG = --enable-rabbit
    - env: CONFIG = --enable-webserver
    - env: CONFIG = --enable-ocsp
    - env: CONFIG = --enable-crl
    - env: CONFIG = --enable-crl-monitor
    - env: CONFIG = --enable-ntru
    - env: CONFIG = --enable-sni
    - env: CONFIG = --enable-maxfragment
    - env: CONFIG = --enable-truncatedhmac
    - env: CONFIG = --enable-tlsx
    - env: CONFIG = --enable-testcert
    - env: CONFIG = --enable-fastmath
    - env: CONFIG = --enable-fasthugemath
    - env: CONFIG = --enable-mcapi
    - env: CONFIG = --enable-gcc-hardening
    
script: 
  - ./configure $CONFIG && make
